### ISSUE TITLE
How to format 'thought breaks' e.g. 3 asterisks

### ISSUE THREAD

**Issue by samwilson** [gitenberg-dev/documentation#13]
Many books have so-called thought breaks, like this:

---

How should they be formatted?

**Comment by samwilson** [comment]
Oh, Github knows! It's turned my three asterisks into a horizontal rule.

**Comment by sethwoodworth** [comment]
http://asciidoctor.org/docs/user-manual/#horizontal-rules

Asciidoctor also supports `***`  But the most universal way of denoting an
HR is `'''` this will work on asciidoc and asciidoctor

**Comment by samwilson** [comment]
Cool. Three apostrophes it is! I've also sent gitenberg-dev/asciidoctor-htmlbook#2 (I hope I've gotten it correct).
