### ISSUE TITLE
Emphasis preceeding em dashes :(

### ISSUE THREAD

**Issue by samwilson** [gitenberg-dev/documentation#15]
This appears not to work:

```
Lorem _ipsum_—lorem ipsum?
```

So one must use this:

```
Lorem __ipsum__—lorem ipsum?
```

(That's an em dash in there, and double-underscores in the second example.)

I came across this in line 7173 of https://github.com/GITenberg/Thyrza_4302/blob/master/4302.asciidoc

It's not a Gitenberg bug, but I thought I'd raise it here in case any of you know whether this should be reported to Asciidoc? And if so, how?

**Comment by sethwoodworth** [comment]
This is a bug in Asciidoc for sure, or least something that ought to be clarified in their doctumentation.  It's a little unclear from a google search, but the asciidoc org moved development and issue tracking to github: https://github.com/asciidoc/asciidoc/issues

I would report it there, making sure to include the text `gitenberg-dev/documentation/issues/15` in your issue, which will automatically link these two issues.

It's worth noting that asciidoctor doesn't have this issue, but ideally we would not be limited to using either processor.  I am happy with using two underscores to preserve compatibility.

test.asciidoc:

``` asciidoc
Lorem _ipsum_—lorem ipsum?

Lorem _ipsum_ lorem ipsum?

Lorem __ipsum__—lorem ipsum?
```

`asciidoctor test.asciidoc; firefox test.html`

Looks like:

![lorem ipsum x3](https://cloud.githubusercontent.com/assets/123998/9224168/70d964c4-40ce-11e5-9c9a-7b48c0bd3596.png)

`asciidoc test asciidoc; firefox test.html`  looks like

![2015-08-12-091820_2560x1600_scrot](https://cloud.githubusercontent.com/assets/123998/9224805/4be02540-40d3-11e5-986e-e4019b25c1a0.png)

**Comment by samwilson** [comment]
Oh, it's good that asciidoctor works properly. But yeah, I'd say it _should_ work with single underscores; that'd make more sense.

I've raised it as asciidoc/asciidoc/issues/86

Thanks Seth!

**Comment by samwilson** [comment]
It's correct behaviour: http://asciidoc.org/userguide.html#X52

> Constrained quotes
> 
> Quoted must be bounded by white space or commonly adjoining punctuation characters. These are the most commonly used type of quote.
> 
> Unconstrained quotes
> 
> Unconstrained quotes have no boundary constraints and can be placed anywhere within inline text.
